name: testing

on: [pull_request]

jobs:
  plot_publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r doc/requirements.txt

    - name: Render
      run: |
        cd doc
        make render

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: doc/build
